# This is a basic workflow to help you get started with Actions

name: nightly-build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  schedule:
    # 20:00 JST
    - cron: "0 11 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y uuid-dev

      - name: Cache LLVM artifact
        id: cache-llvm
        uses: actions/cache@v2
        with:
          path: |
            ./thirdparty/llvm-project
          key: ${{ runner.os }}-norm-${{ hashFiles('thirdparty/llvm-project/llvm/CMakeLists.txt') }}

      - name: Build with the latest LLVM
        if: steps.cache-llvm.outputs.cache-hit != 'true'
        run: |
          ./update-llvm.sh
